#!/bin/sh
set -er
TASK=$1

# Config
LOCAL="/Users/bruno/backup/"
EXTRA=""
RSYNC="rsync --recursive --times --progress --links --hard-links --fuzzy --delete-before --delete-excluded --exclude @eaDir"

# Do the job !

case $TASK in

	svn|git|mail)
		REMOTE=marlin.bmconseil.com
		;;

#	svn|git)
#		REMOTE=marlin.bmconsel
#		;;

	photo)
		REMOTE=nemo
    EXTRA="\
      --exclude photos1997 --exclude photos1998 --exclude photos1999 \
      --exclude photos2000 --exclude photos2001 --exclude photos2002 \
      --exclude photos2003 --exclude photos2004 --exclude photos2006 \
      --exclude photos2007 \
      "
		;;

	*)
		echo "usage: `basename $0` {svn|git|mail}"
		exit 1
		;;
esac


echo "####################################################"
echo "Syncing <$TASK> ..."
echo "####################################################"
$RSYNC "$REMOTE"::"$TASK"/ "$LOCAL/$TASK" $EXTRA
echo "####################################################"
echo "Done !"
echo "####################################################"

