#! /bin/sh
set -ere
TASK=$1
HOST=$2


# Config
#HTTP_MIRROR=gulus.usherbrooke.ca
#HTTP_MIRROR=non-us.debian.org
#HTTP_MIRROR=ftp.proxad.net 
HTTP_MIRROR=mir2.ovh.net 
#HTTP_MIRROR=ftp.thaios.net 
#HTTP_MIRROR=ftp.be.debian.org 
#HTTP_MIRROR=ftp.fr.debian.org 
#HTTP_MIRROR=debian.ens-cachan.fr
LOCALDIR=/Users/bruno/cache/debian/
#LOCALDIR=/Volumes/debian_nfs/
RSYNC_UPDATE_ATTRIBS="--recursive --times --progress --delete --links --copy-dirlinks --hard-links --fuzzy --delete-before"

# Do the job !
umask 002
case $TASK in

	from)
		rsync "$HOST"::debian/ "$LOCALDIR" $RSYNC_UPDATE_ATTRIBS
		;;

	to)
		rsync "$LOCALDIR" "$HOST"::debian/ $RSYNC_UPDATE_ATTRIBS
		;;

	update | up)
		debmirror "$LOCALDIR" \
			--host=$HTTP_MIRROR \
			--method=http \
			--progress --cleanup --no-source --getcontents \
			--dist=testing,unstable,experimental -arch=amd64 \
			--exclude-deb-section=embedded,hamradio \
			--section=main,contrib,non-free,non-us,main/debian-installer \
			--ignore-release-gpg \
			--exclude='openarena.*' \
			--exclude='supertuxkart' \
			--exclude='wesnoth' 
		;;
		#--ignore-release-gpg --pdiff=mirror -\

	*)
		echo "usage: $0 {update|up|from|to} {nemo|hector|geantvert}"
		exit 1
		;;
esac			

#	--dist=testing,unstable,lenny,sid/non-US -arch=i386 \


