#! /bin/sh
set -ere
TASK=$1
P2=$2
P3=$3

# Config
#HTTP_MIRROR=gulus.usherbrooke.ca
#HTTP_MIRROR=non-us.debian.org
#HTTP_MIRROR=ftp.proxad.net 
#HTTP_MIRROR=mir2.ovh.net 
#HTTP_MIRROR=debian.ens-cachan.fr
#HTTP_MIRROR=ftp.thaios.net 
#HTTP_MIRROR=ftp.be.debian.org 
HTTP_MIRROR=ftp.fr.debian.org 
LOCALDIR=/mirrors/debian/
RSYNC_UPDATE_ATTRIBS="--recursive --times --progress --delete --links"


case $TASK in

	update | up)
		debmirror $LOCALDIR \
			--host=$HTTP_MIRROR \
			--method=http \
			--progress --cleanup --no-source --getcontents \
			--dist=testing,unstable,lenny,sid -arch=i386,amd64 \
			--exclude-deb-section=embedded,hamradio \
			--section=main,contrib,non-free,non-us,main/debian-installer \
			--ignore-release-gpg --pdiff=mirror -\
			--exclude='openarena.*' \
			--exclude='supertuxkart' \
			--exclude='wesnoth' 
		;;
	*)
		echo "usage: $0 {up|update|to-nemo|to-hector|from-nemo|from-hector}"
		exit 1
		;;
esac			

#	--dist=testing,unstable,lenny,sid/non-US -arch=i386 \

